name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v1
    with:
      python-version: '3.12'

  test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v1
    with:
      python-version: '3.12'
